web_config:
  host: "localhost"
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s

postgres_config:
  host: "localhost"
  port: "5432"
  user: "dev"
  password: "qqq"
  db_name: "mydb"
  sslmode: false

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db_name: 0

kafka:
  brokers:
    # - "localhost:9092"
    - "localhost:9092"
    - "localhost:9094"
    - "localhost:9096"
    - "localhost:9098"
  topic: "orders_new_event"
  partition: 0
  min_bytes: 1
  max_bytes: 10e6
  group_id: "my-test-id"

initial_data_size: 100
